services:
    facefusion-cuda:
        build:
            context: .
            dockerfile: Dockerfile.cuda
        command: [ 'python', 'server.py' ]
        volumes:
            - .assets:/facefusion/.assets
        ports:
            - 8000:8000
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            capabilities: [ gpu, video ]
